set(NAME "aim")

set(SRCS
    "audio/sound.cc"
    "audio/sound.h"
    "audio/sound_manager.cc"
    "audio/sound_manager.h"
    "common/backup.cc"
    "common/backup.h"
    "common/collections.cc"
    "common/collections.h"
    "common/field.h"
    "common/files.cc"
    "common/files.h"
    "common/lazy_cache.h"
    "common/geometry.cc"
    "common/geometry.h"
    "common/system.cc"
    "common/system.h"
    "common/imgui_ext.cc"
    "common/imgui_ext.h"
    "common/implot_ext.cc"
    "common/implot_ext.h"
    "common/log.h"
    "common/mat_icons.h"
    "common/name_util.cc"
    "common/name_util.h"
    "common/object_type.h"
    "common/proto_util.cc"
    "common/proto_util.h"
    "common/random.h"
    "common/resource_name.h"
    "common/search.cc"
    "common/search.h"
    "common/simple_types.h"
    "common/times.cc"
    "common/times.h"
    "common/util.cc"
    "common/util.h"
    "common/wall.cc"
    "common/wall.h"
    "core/application.cc"
    "core/application.cc"
    "core/application.h"
    "core/application.h"
    "core/application_state.cc"
    "core/application_state.cc"
    "core/application_state.h"
    "core/application_state.h"
    "core/bundle_manager.cc"
    "core/bundle_manager.h"
    "core/camera.cc"
    "core/camera.h"
    "core/displays.h"
    "core/file_system.cc"
    "core/file_system.h"
    "core/font_manager.cc"
    "core/font_manager.h"
    "core/guide_manager.cc"
    "core/guide_manager.h"
    "core/history_manager.cc"
    "core/history_manager.h"
    "core/labels_manager.cc"
    "core/labels_manager.h"
    "core/local_store.cc"
    "core/local_store.h"
    "core/msaa.cc"
    "core/msaa.h"
    "core/perf.cc"
    "core/perf.h"
    "core/play_time_manager.cc"
    "core/play_time_manager.h"
    "core/playlist_manager.cc"
    "core/playlist_manager.h"
    "core/process_lock.cc"
    "core/process_lock.h"
    "core/profile_selection.h"
    "core/replay_manager.cc"
    "core/replay_manager.h"
    "core/scenario_manager.cc"
    "core/scenario_manager.h"
    "core/screen.cc"
    "core/screen.h"
    "core/settings_manager.cc"
    "core/settings_manager.h"
    "core/stats_manager.cc"
    "core/stats_manager.h"
    "core/target.cc"
    "core/target.h"
    "core/version.h"
    "database/aim_db.cc"
    "database/aim_db.h"
    "database/local_store_db.cc"
    "database/local_store_db.h"
    "database/sqlite_util.h"
    "graphics/crosshair_renderer.cc"
    "graphics/crosshair_renderer.h"
    "graphics/draw_data.cc"
    "graphics/draw_data.h"
    "graphics/image.cc"
    "graphics/image.h"
    "graphics/renderer.cc"
    "graphics/renderer.h"
    "graphics/shapes.cc"
    "graphics/shapes.h"
    "graphics/textures.cc"
    "graphics/textures.h"
    "proto/bundle.pb.cc"
    "proto/bundle.pb.h"
    "proto/common.pb.cc"
    "proto/common.pb.h"
    "proto/crosshair.pb.cc"
    "proto/crosshair.pb.h"
    "proto/guide.pb.cc"
    "proto/guide.pb.h"
    "proto/playlist.pb.cc"
    "proto/playlist.pb.h"
    "proto/scenario.pb.cc"
    "proto/scenario.pb.h"
    "proto/settings.pb.cc"
    "proto/settings.pb.h"
    "proto/stats.pb.cc"
    "proto/stats.pb.h"
    "proto/theme.pb.cc"
    "proto/theme.pb.h"
    "scenario/base_scenario.cc"
    "scenario/base_scenario.h"
    "scenario/basic_movement_controller.cc"
    "scenario/basic_movement_controller.h"
    "scenario/metronome.cc"
    "scenario/metronome.h"
    "scenario/replay.cc"
    "scenario/replay.h"
    "scenario/replay_viewer.cc"
    "scenario/replay_viewer.h"
    "scenario/scenario.cc"
    "scenario/scenario.h"
    "scenario/scenario_factory.cc"
    "scenario/scenario_factory.h"
    "scenario/scenario_overrides.cc"
    "scenario/scenario_overrides.h"
    "scenario/scenario_timer.cc"
    "scenario/scenario_timer.h"
    "scenario/scenario_util.cc"
    "scenario/scenario_util.h"
    "scenario/target_placement.cc"
    "scenario/target_placement.h"
    "scenario/tracking_sound.h"
    "scenario/types/angle_strafe_scenario.cc"
    "scenario/types/barrel_scenario.cc"
    "scenario/types/bounce_scenario.cc"
    "scenario/types/centering_scenario.cc"
    "scenario/types/circle_scenario.cc"
    "scenario/types/linear_scenario.cc"
    "scenario/types/sine_scenario.cc"
    "scenario/types/static_scenario.cc"
    "scenario/types/strafe_scenario.cc"
    "scenario/types/wall_arc_scenario.cc"
    "scenario/types/wall_wander_scenario.cc"
    "scenario/types/waypoint_scenario.cc"
    "scenario/waypoint_movement_controller.cc"
    "scenario/waypoint_movement_controller.h"
    "ui/bundle_ui.cc"
    "ui/bundle_ui.h"
    "ui/copy_playlist_dialog.cc"
    "ui/copy_playlist_dialog.h"
    "ui/crosshair_editor_screen.cc"
    "ui/crosshair_editor_screen.h"
    "ui/drag_and_drop.cc"
    "ui/drag_and_drop.h"
    "ui/editor/profile_list_editor.h"
    "ui/editor/room_editor.cc"
    "ui/editor/room_editor.h"
    "ui/editor/scenario_editor_common.cc"
    "ui/editor/scenario_editor_common.h"
    "ui/editor/scenario_editor_screen.cc"
    "ui/editor/scenario_editor_screen.h"
    "ui/editor/scenario_type_editor.cc"
    "ui/editor/scenario_type_editor.h"
    "ui/editor/target_editor.cc"
    "ui/editor/target_editor.h"
    "ui/guide_editor_screen.cc"
    "ui/guide_editor_screen.h"
    "ui/playlist_editor_screen.cc"
    "ui/playlist_editor_screen.h"
    "ui/base_editor_screen.cc"
    "ui/base_editor_screen.h"
    "ui/guide_ui.cc"
    "ui/guide_ui.h"
    "ui/home_screen.cc"
    "ui/home_screen.h"
    "ui/object_browser.cc"
    "ui/object_browser.h"
    "ui/play_time_screen.cc"
    "ui/play_time_screen.h"
    "ui/playlist_ui.cc"
    "ui/playlist_ui.h"
    "ui/quick_settings_screen.cc"
    "ui/quick_settings_screen.h"
    "ui/reaction_time_screen.cc"
    "ui/reaction_time_screen.h"
    "ui/scenario_ui.cc"
    "ui/scenario_ui.h"
    "ui/search_selector.cc"
    "ui/search_selector.h"
    "ui/select_object_dialog.cc"
    "ui/select_object_dialog.h"
    "ui/select_variation_dialog.cc"
    "ui/select_variation_dialog.h"
    "ui/settings_screen.cc"
    "ui/settings_screen.h"
    "ui/stats/history_plot.cc"
    "ui/stats/history_plot.h"
    "ui/stats/perf_ui.cc"
    "ui/stats/perf_ui.h"
    "ui/stats/stats_screen.cc"
    "ui/stats/stats_screen.h"
    "ui/theme_editor_screen.cc"
    "ui/theme_editor_screen.h"
    "ui/top_bar.cc"
    "ui/top_bar.h"
    "ui/ui_app.h"
    "ui/ui_screen.cc"
    "ui/ui_screen.h"
)

add_library(${NAME} ${SRCS})

add_subdirectory(analysis)

target_link_libraries(
    ${NAME}
    PUBLIC
    SDL3::SDL3
    SDL3_mixer::SDL3_mixer
    SDL_image
    absl::strings
    absl::flags
    glm::glm
    imgui
    implot
    sqlite3
    protobuf::libprotobuf
    spdlog)

include(warnings.cmake)
target_compile_options(${NAME} PRIVATE ${PROJECT_WARNING_FLAGS})

target_include_directories(${NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/..)

set_target_properties(${NAME} PROPERTIES COMPILE_WARNING_AS_ERROR ON)
